version: '3.8'

services:
    postgres:
        image: postgres:16
        container_name: postgreSQL
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: admin
            POSTGRES_DB: finance
        ports:
            - '5432:5432'
        volumes:
            - postgres_data:/var/lib/postgresql/data
            - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    backend:
        container_name: backend
        build: ./backend
        ports:
            - '3000:3000'
        volumes:
            - ./backend:/usr/src/app:delegated
        command: npm run dev
        depends_on:
            - postgres

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - '5173:5173'
        volumes:
            - ./frontend:/app
            - /app/node_modules
        environment:
            - CHOKIDAR_USEPOLLING=true

volumes:
    postgres_data:
